In [ ]:
from scipy.stats import entropy
from scipy.special import rel_entr
from sklearn.metrics import accuracy_score, confusion_matrix
import random
import numpy as np
import torch
import gdown

In [ ]:
import pickle
from sklearn.metrics import roc_auc_score

# Logit URLs and Paths.

This is the only cell to be changed when swapping between different datasets

## Imagenet

In [ ]:
base_url = 'https://drive.google.com/uc?id='


clean_train_min = base_url + '1mqGyx_tqnlrxX3JKftWmxq4KzJ5aCoLf'
poison_train_min = base_url + '1seswMPWJ4mlxxTqA24JIdPIeEpwC7emm'
clean_train_max = base_url + '1qDAw8pImTRNB-l8txrNC8X5MOXtah1Wr'
poison_train_max = base_url + '1jU8pHDCAXgNAHHgPnX2OHdiDOQp2odvN'


clean_test_min = base_url + '1QhzJv6Mbd0dJ0NMB7Od9HrTI67UgAPcI'
poison_test_min = base_url + '1SaLZ6dpg3a8F1SsJdz0HTr-n-F5eiq1P'
clean_test_max = base_url + '18tn5SokPljlGtF3moZpCIzU0jQvNkGXF'
poison_test_max = base_url + '1uMFPEv534GeeRCA5rFjldyHW8wXHNWMD'



gdown.download(clean_train_min)
gdown.download(poison_train_min)
gdown.download(clean_train_max)
gdown.download(poison_train_max)
gdown.download(clean_test_min)
gdown.download(poison_test_min)
gdown.download(clean_test_max)
gdown.download(poison_test_max)



train_clean_min_path = '/content/imagenet_clean_logits.pkl'
train_poison_min_path = '/content/imagenet_poisoned_logits.pkl'
train_clean_max_path = '/content/imagenet_clean_logits_max.pkl'
train_poison_max_path = '/content/imagenet_poisoned_logits_max.pkl'

test_clean_min_path = '/content/imagenet_clean_logits_test.pkl'
test_poison_min_path = '/content/imagenet_poisoned_logits_test.pkl'
test_clean_max_path = '/content/imagenet_clean_logits_max_test.pkl'
test_poison_max_path = '/content/imagenet_poisoned_logits_max_test.pkl'

## Tiny Imagenet

In [ ]:
base_url = 'https://drive.google.com/uc?id='

all_zipped = '1oeUigoG18APiZjLbJuhWeHEF1LeT_nHP'


gdown.download(base_url+all_zipped)

# unzip file
!unzip tiny.zip -d ./


train_clean_min_path = '/content/tiny_clean_min_train_logits.pkl'
train_poison_min_path = '/content/tiny_poisoned_min_train_logits.pkl'
train_clean_max_path = '/content/tiny_clean_max_train_logits.pkl'
train_poison_max_path = '/content/tiny_poisoned_max_train_logits.pkl'

test_clean_min_path = '/content/tiny_clean_min_test_logits.pkl'
test_poison_min_path = '/content/tiny_poisoned_min_test_logits.pkl'
test_clean_max_path = '/content/tiny_clean_max_test_logits.pkl'
test_poison_max_path = '/content/tiny_poisoned_max_test_logits.pkl'

Downloading...
From (original): https://drive.google.com/uc?id=1oeUigoG18APiZjLbJuhWeHEF1LeT_nHP
From (redirected): https://drive.google.com/uc?id=1oeUigoG18APiZjLbJuhWeHEF1LeT_nHP&confirm=t&uuid=1c1be6e6-c8ed-49c9-a357-0def774d9a83
To: /content/tiny.zip

  0%|          | 0.00/641M [00:00<?, ?B/s]
  0%|          | 1.57M/641M [00:00<00:41, 15.4MB/s]
  0%|          | 3.15M/641M [00:00<00:54, 11.7MB/s]
  1%|          | 5.77M/641M [00:00<00:50, 12.5MB/s]
  2%|▏         | 15.7M/641M [00:00<00:20, 30.0MB/s]
  3%|▎         | 22.0M/641M [00:00<00:16, 37.4MB/s]
  5%|▍         | 29.9M/641M [00:00<00:15, 39.2MB/s]
  6%|▌         | 38.8M/641M [00:01<00:12, 49.2MB/s]
  7%|▋         | 44.6M/641M [00:01<00:13, 44.0MB/s]
  8%|▊         | 50.9M/641M [00:01<00:12, 46.9MB/s]
  9%|▉         | 58.7M/641M [00:01<00:10, 54.5MB/s]
 10%|█         | 65.0M/641M [00:01<00:10, 53.4MB/s]
 11%|█▏        | 73.4M/641M [00:01<00:11, 49.9MB/s]
 13%|█▎        | 84.9M/641M [00:01<00:10, 52.9MB/s]
 15%|█▍        | 94.9M/64

Archive:  tiny.zip
  inflating: ./tiny_clean_max_test_logits.pkl  
  inflating: ./tiny_clean_max_train_logits.pkl  

  4%|▍         | 89.1M/2.00G [00:19<00:16, 113MB/s]


  inflating: ./tiny_clean_min_test_logits.pkl  
  inflating: ./tiny_clean_min_train_logits.pkl  
  inflating: ./tiny_poisoned_max_test_logits.pkl  
  inflating: ./tiny_poisoned_max_train_logits.pkl  
  inflating: ./tiny_poisoned_min_test_logits.pkl  
  inflating: ./tiny_poisoned_min_train_logits.pkl  


## CIFAR-10

In [ ]:
base_url = 'https://drive.google.com/uc?id='


clean_train_min = base_url + '1_nRyX_mK69u95iuqcBWh-V4tEZ1syA-V'
poison_train_min = base_url + '1EACBnWhqB_4qhhJt1yXlXyZGlBiDaRzn'
clean_train_max = base_url + '1jySfnLTdTg3oidiHbd2OzzJmFOJCDQ8j'
poison_train_max = base_url + '1hx0KqcGQIYDJ8tYcgJjq35wCNAAa3VhJ'


clean_test_min = base_url + '11o7g69dpSvOLc96_Wg1G9003M9NtyqGs'
poison_test_min = base_url + '1U5vljmjPgCZ_b7cEjhgV97on-xo8AaMd'
clean_test_max = base_url + '1_sh546aXQrTtG0luS2Z1H_JMrIEqKJpV'
poison_test_max = base_url + '1cZCKl_Z5i9Iv67qPS7jP-GdwzuQ3nDTN'



gdown.download(clean_train_min)
gdown.download(poison_train_min)
gdown.download(clean_train_max)
gdown.download(poison_train_max)
gdown.download(clean_test_min)
gdown.download(poison_test_min)
gdown.download(clean_test_max)
gdown.download(poison_test_max)



train_clean_min_path = '/content/cifar_clean_min_train_logits.pkl'
train_poison_min_path = '/content/cifar_poisoned_min_train_logits.pkl'
train_clean_max_path = '/content/cifar_clean_max_train_logits.pkl'
train_poison_max_path = '/content/cifar_poisoned_max_train_logits.pkl'

test_clean_min_path = '/content/cifar_clean_min_test_logits.pkl'
test_poison_min_path = '/content/cifar_poisoned_min_test_logits.pkl'
test_clean_max_path = '/content/cifar_clean_max_test_logits.pkl'
test_poison_max_path = '/content/cifar_poisoned_max_test_logits.pkl'

Downloading...
From: https://drive.google.com/uc?id=17ApJnR10LWiaGjjseQ-vRBgw_8MUY1fd
To: /content/ulp_cifar_10.zip
100%|██████████| 316k/316k [00:00<00:00, 4.97MB/s]


# Utils

In [ ]:
# Function to load and convert tensors to float16
def load_and_convert(filepath):
    with open(filepath, 'rb') as f:
        data = pickle.load(f)
    return {k: v.to(torch.float16) for k, v in data.items()}  # Convert tensors to float16



class Evaluator:
  @staticmethod
  def get_accuracy(y_true, y_pred):
    return accuracy_score(y_true, y_pred)

  @staticmethod
  def get_confusion_matrix(y_true, y_pred):
    return confusion_matrix(y_true, y_pred)

  @staticmethod
  def get_auc(y_true, y_anomaly_scores):
    return roc_auc_score(y_true, y_anomaly_scores)

# Detectors

In [ ]:
class GaussianDetector:
    """
    A detector that computes anomaly scores based on Gaussian log probability.

    Configuration parameters:
      - method: 'voting' or 'diagonal'
            (voting: uses softmax over the entire logit matrix,
             diagonal: uses only the main-diagonal entries)
      - standardized: bool, whether to apply standardization to the logits.

    The detector first estimates the mean and std vectors (the "clean signature") from a set of clean models.
    It can then compute an anomaly score for each new model and determine an optimal threshold by comparing
    known clean and poisoned models.
    """
    def __init__(self, method='voting', standardized=False):
        assert method in ['voting', 'diagonal'], f"Invalid method: {method}"
        self.method = method
        self.standardized = standardized

        # Will be set via set_parameters()
        self.clean_signature_means = None
        self.clean_signature_stds = None
        self.optimal_threshold = None

    def compute_feature(self, logits):
        """
        Computes the feature vector for a given logit matrix.

        For method 'voting':
          - If standardized: each row is standardized before applying softmax,
            then the probabilities are averaged over rows.
          - Else: directly apply softmax and take the mean over rows.

        For method 'diagonal':
          - If standardized: standardize the diagonal entries.
          - Else: simply extract the diagonal as the feature.
        """
        eps = 1e-7
        if self.method == 'voting':
            if self.standardized:
                # Standardize each row before softmax.
                logits_std = (logits - logits.mean(dim=1, keepdim=True)) / (logits.std(dim=1, keepdim=True) + eps)
                feature = torch.softmax(logits_std, dim=1).mean(dim=0)
            else:
                feature = torch.softmax(logits, dim=1).mean(dim=0)
        elif self.method == 'diagonal':
            # Extract the diagonal entries (convert to float32 for numerical stability)
            raw_diag = torch.diagonal(logits, dim1=0, dim2=1).to(torch.float32)
            if self.standardized:
                feature = (raw_diag - raw_diag.mean()) / (raw_diag.std() + eps)
            else:
                feature = raw_diag
        else:
            raise ValueError("Invalid method selected.")
        return feature

    def set_parameters(self, clean_logits_tensor):
        """
        Estimates the clean signature parameters from a tensor of clean logits.

        clean_logits_tensor: tensor of shape (num_models, num_classes, num_classes)
        """
        features = []
        for i in range(clean_logits_tensor.size(0)):
            feat = self.compute_feature(clean_logits_tensor[i])
            features.append(feat)
        features = torch.stack(features)  # (num_models, num_classes)
        self.clean_signature_means = features.mean(dim=0)
        self.clean_signature_stds = features.std(dim=0)

    def compute_log_prob(self, feature_vector):
        """
        Computes the log probability of a feature vector under the global Gaussian signature.
        """
        eps = 1e-7
        stds = self.clean_signature_stds.to(torch.float32) + eps
        means = self.clean_signature_means.to(torch.float32)
        # Gaussian log probability (up to a constant)
        log_probs = -0.5 * torch.log(2 * torch.pi * (stds**2)) - ((feature_vector - means)**2 / (2 * stds**2))
        return log_probs.sum()

    def compute_anomaly(self, logits):
        """
        Computes the anomaly score (negative log probability) for given logits.
        """
        feature = self.compute_feature(logits)
        return -self.compute_log_prob(feature)

    def get_optimal_threshold(self, model_instances):
        """
        Compute an optimal threshold based on anomaly scores and known ground-truth.
        model_instances: list of InputModel objects.
        The anomaly score threshold is chosen to maximize accuracy.
        """
        scores = torch.tensor([model.anomaly_score for model in model_instances])
        labels = torch.tensor([1 if model.model_type == 'poison' else 0 for model in model_instances])
        thresholds = torch.sort(scores)[0]

        best_acc = 0.0
        best_threshold = None

        for t in thresholds:
            preds = (scores > t).int()  # Classify as 'poison' when anomaly score exceeds threshold.
            acc = (preds == labels).float().mean().item()
            if acc > best_acc:
                best_acc = acc
                best_threshold = t.item()

        self.optimal_threshold = best_threshold
        return best_acc, best_threshold


class InputModel:
    """
    A lightweight model wrapper that computes its anomaly score using a given detector.

    Parameters:
       - model_id: an identifier for the model
       - logits: tensor of shape (num_classes, num_classes)
       - model_type: string, either 'clean' or 'poison'
       - detector: an instance of GaussianDetector, used to compute the anomaly score.
    """
    def __init__(self, model_id, logits, model_type, detector: GaussianDetector):
        assert model_type in ['clean', 'poison'], f'Invalid model type: {model_type}'
        self.model_id = model_id
        self.model_type = model_type
        self.anomaly_score = detector.compute_anomaly(logits)



def train_detector(detector, train_clean_path, train_poison_path):
    """
    Trains the detector using clean and poisoned logits from training files.

    detector: an instance of GaussianDetector.
    train_clean_path, train_poison_path: filepaths for training data.

    Returns a dictionary of anomaly scores separated by model type.
    """
    # Load and process training data
    clean_logits = load_and_convert(train_clean_path)
    poison_logits = load_and_convert(train_poison_path)

    # Set global parameters using only clean models.
    clean_tensor = torch.stack([clean_logits[key] for key in clean_logits])
    detector.set_parameters(clean_tensor)

    # Construct training models.
    training_models = []
    for model_id in clean_logits:
        training_models.append(InputModel(model_id, clean_logits[model_id], 'clean', detector))
    for model_id in poison_logits:
        training_models.append(InputModel(model_id, poison_logits[model_id], 'poison', detector))

    # Optimize threshold.
    train_acc, optimal_threshold = detector.get_optimal_threshold(training_models)

    # Evaluate performance.
    y_true = []
    y_pred = []
    y_anomaly_scores = []
    anomaly_scores_dict = {'clean': [], 'poison': []}
    for m in training_models:
        y_true.append(1 if m.model_type == 'poison' else 0)
        y_pred.append(1 if m.anomaly_score > detector.optimal_threshold else 0)
        y_anomaly_scores.append(m.anomaly_score)
        anomaly_scores_dict[m.model_type].append(m.anomaly_score)

    acc = Evaluator.get_accuracy(y_true, y_pred)
    conf_matrix = Evaluator.get_confusion_matrix(y_true, y_pred)
    #auc = Evaluator.get_auc(y_true, y_anomaly_scores)

    print(f'Train Optimal Accuracy: {train_acc}')
    print(f'Training Accuracy (Evaluator): {acc}')
    print(f'Confusion Matrix:\n{conf_matrix}')
    #print(f'AUC: {auc}')

    anomaly_scores_dict['clean'] = np.array(anomaly_scores_dict['clean'])
    anomaly_scores_dict['poison'] = np.array(anomaly_scores_dict['poison'])
    return anomaly_scores_dict


def test_detector(detector, test_clean_path, test_poison_path):
    """
    Evaluates the detector on test data.

    detector: an instance of GaussianDetector with parameters and threshold previously set.
    test_clean_path, test_poison_path: filepaths for test data.

    Returns a dictionary of anomaly scores separated by model type.
    """
    # Load test data.
    clean_logits = load_and_convert(test_clean_path)
    poison_logits = load_and_convert(test_poison_path)

    test_models = []
    for model_id in clean_logits:
        test_models.append(InputModel(model_id, clean_logits[model_id], 'clean', detector))
    for model_id in poison_logits:
        test_models.append(InputModel(model_id, poison_logits[model_id], 'poison', detector))

    y_true = []
    y_pred = []
    y_anomaly_scores = []
    anomaly_scores_dict = {'clean': [], 'poison': []}

    for m in test_models:
        y_true.append(1 if m.model_type == 'poison' else 0)
        y_pred.append(1 if m.anomaly_score > detector.optimal_threshold else 0)
        y_anomaly_scores.append(m.anomaly_score)
        anomaly_scores_dict[m.model_type].append(m.anomaly_score)

    acc = Evaluator.get_accuracy(y_true, y_pred)
    conf_matrix = Evaluator.get_confusion_matrix(y_true, y_pred)
    auc = Evaluator.get_auc(y_true, y_anomaly_scores)

    print(f'Test Accuracy: {acc}')
    print(f'Confusion Matrix:\n{conf_matrix}')
    print(f'AUC: {auc}')

    anomaly_scores_dict['clean'] = np.array(anomaly_scores_dict['clean'])
    anomaly_scores_dict['poison'] = np.array(anomaly_scores_dict['poison'])
    return anomaly_scores_dict



# Min Votes

In [ ]:
min_detector = GaussianDetector(method='voting', standardized=True)
min_train_scores = train_detector(min_detector, train_clean_min_path, train_poison_min_path)
min_test_scores  = test_detector(min_detector, test_clean_min_path, test_poison_min_path)

AttributeError: 'Tensor' object has no attribute 'items'

# Max Diagonal

In [ ]:
max_detector = GaussianDetector(method='diagonal', standardized=True)
max_train_scores = train_detector(max_detector, train_clean_max_path, train_poison_max_path)
max_test_scores  = test_detector(max_detector, test_clean_max_path, test_poison_max_path)

Train Optimal Accuracy: 1.0
Training Accuracy (Evaluator): 1.0
Confusion Matrix:
[[  6   0]
 [  0 500]]
Test Accuracy: 0.5
Confusion Matrix:
[[  0 100]
 [  0 100]]
AUC: 0.6465


# Both (Min + Max Anomaly scores)

In [ ]:
class MinMaxEnsembler:
  optimal_threshold = None

  def __init__(self, method='sum scores', standardized=False):
        assert method in ['sum scores'], f"Invalid method: {method}"
        self.method = method

  def get_optimal_threshold(self, min_anomaly_scores_dict, max_anomaly_scores_dict):
    '''
    min_anomaly_scores_dict: {'clean': (num_models,), 'poison': (num_models,)}
    max_anomaly_scores_dict: {'clean': (num_models,), 'poison': (num_models,)}
    '''

    if self.method == 'sum scores':
      clean_summed_scores = min_anomaly_scores_dict['clean'] + max_anomaly_scores_dict['clean']
      poison_summed_scores = min_anomaly_scores_dict['poison'] + max_anomaly_scores_dict['poison']

    scores = np.concatenate([clean_summed_scores, poison_summed_scores])
    labels = np.concatenate([np.zeros(len(clean_summed_scores)), np.ones(len(poison_summed_scores))])

    thresholds = np.sort(scores)

    best_acc = 0.0
    best_threshold = None

    for t in thresholds:
        preds = (scores > t).astype(int)
        acc = (preds == labels).mean()
        if acc > best_acc:
            best_acc = acc
            best_threshold = t

    self.optimal_threshold = best_threshold
    return best_acc, best_threshold


def train_both(ensembler, train_min_anomaly_scores, train_max_anomaly_scores):
  ensembler.get_optimal_threshold(train_min_anomaly_scores, train_max_anomaly_scores)
  num_models = len(train_min_anomaly_scores['clean'])
  y_true = []
  y_pred = []
  y_anomaly_scores = []

  for model_type in ['clean', 'poison']:
    for model_idx in range(num_models):
      y_true.append(1 if model_type == 'poison' else 0)
      y_anomaly_scores.append(train_min_anomaly_scores[model_type][model_idx] + train_max_anomaly_scores[model_type][model_idx])



  y_true = np.array(y_true).astype(int)
  y_anomaly_scores = np.array(y_anomaly_scores)
  y_pred = (y_anomaly_scores > ensembler.optimal_threshold).astype(int)


  acc = Evaluator.get_accuracy(y_true, y_pred)
  conf_matrix = Evaluator.get_confusion_matrix(y_true, y_pred)
  #auc = Evaluator.get_auc(y_true, y_anomaly_scores)

  print(f'Train Accuracy: {acc}')
  print(f'Confusion Matrix:\n{conf_matrix}')
  #print(f'AUC: {auc}')





def test_both(ensembler, test_min_anomaly_scores, test_max_anomaly_scores):
  num_models = len(test_min_anomaly_scores['clean'])
  y_true = []
  y_pred = []
  y_anomaly_scores = []

  for model_type in ['clean', 'poison']:
    for model_idx in range(num_models):
      y_true.append(1 if model_type == 'poison' else 0)
      y_anomaly_scores.append(test_min_anomaly_scores[model_type][model_idx] + test_max_anomaly_scores[model_type][model_idx])

  y_true = np.array(y_true).astype(int)
  y_anomaly_scores = np.array(y_anomaly_scores)
  y_pred = (y_anomaly_scores > ensembler.optimal_threshold).astype(int)

  acc = Evaluator.get_accuracy(y_true, y_pred)
  conf_matrix = Evaluator.get_confusion_matrix(y_true, y_pred)
  auc = Evaluator.get_auc(y_true, y_anomaly_scores)

  print(f'Test Accuracy: {acc}')
  print(f'Confusion Matrix:\n{conf_matrix}')
  print(f'AUC: {auc}')


min_max_ensemble = MinMaxEnsembler()
train_both(min_max_ensemble, min_train_scores, max_train_scores)
test_both(min_max_ensemble, min_test_scores, max_test_scores)

Train Accuracy: 0.9885
Confusion Matrix:
[[999   1]
 [ 22 978]]
Test Accuracy: 0.99
Confusion Matrix:
[[99  1]
 [ 1 99]]
AUC: 0.9998
